### ISSUE TITLE
Error "accces denied for command ts"

### ISSUE THREAD

**Issue by idahopatato** [Sonoran-Software/sonoran_trafficstop#3]
So i am working on the plugin, and all other plugins are working correctly (except Livemap) and I am able to use the /ts but others are not. The server I have in ran by me and I am listed in vMenu admin.group. 

How can I set permission for that to everyone?

**Comment by nathanctech** [comment]
Hi,

Github issues are for defects with the actual plugin itself, not for providing support. Please open a support ticket with Sonoran. You can also view the setup instructions here: https://info.sonorancad.com/integration-plugins/integration-plugins/available-plugins/traffic-stop
